"""MCP tools for AI-generated storyboard frames.

Agents use generate_storyboard_frame() during the ideation and storyboard phases
to produce visual reference panels for planned (future) videos.  Each call:
  1. Generates a PNG via gpt-image-1.5 (fast, low quality — planning images only).
  2. Saves it to the storyboard_frames table.
  3. Creates a canvas artifact of type 'frame' containing the image, so it appears
     on the canvas immediately without a separate create_artifact call.

The HTTP route GET /api/storyboard/{storyboard_frame_id} serves the image.
"""

from typing import Optional

from fastmcp import FastMCP

import db
import dev_events
import image_gen


def register(mcp: FastMCP) -> None:

    @mcp.tool()
    def generate_storyboard_frame(
        project_id: str,
        concept: str,
        shot_type: Optional[str] = "medium shot",
        aspect_ratio: Optional[str] = "1:1",
        creator_id: Optional[str] = None,
        position: Optional[dict] = None,
    ) -> dict:
        """
        Generate an AI image for a planned video scene and add it to the canvas.

        Call this during the **ideation** or **storyboard** phase to visualise a
        planned shot or scene for a future video.  Each call produces one panel.
        For a full storyboard, call once per key scene (typically 4-8 panels).

        The image is generated by gpt-image-1.5 and saved permanently to the
        database.  It also appears on the canvas immediately as a 'frame' artifact
        with an image element whose src is '/api/storyboard/{storyboard_frame_id}'.

        Args:
            project_id:   The active project.
            concept:      Plain-language scene description, e.g.
                          "Creator at a neon-lit desk reviewing analytics late at night,
                           close-up on the monitor glow reflecting off their face."
                          Be specific — lighting, mood, subjects, action all matter.
            shot_type:    Cinematography framing: "close-up", "medium shot" (default),
                          "wide shot", "over-the-shoulder", "POV", "aerial", "insert".
            aspect_ratio: "1:1" (default square) or "16:9" (widescreen panels).
            creator_id:   Optional.  When provided, the creator's style profile
                          (lighting, colour palette, mood) is automatically injected
                          as generation hints so panels match the creator's aesthetic.
            position:     Optional {x, y, w, h} canvas position for the artifact.
                          If omitted, the canvas auto-places it.

        Returns:
            {storyboard_frame_id, image_url, artifact_id, concept, shot_type}

        Tip: string multiple panels together in a single agent turn — call this
        tool 4-8 times for a scene-by-scene storyboard, positioning each artifact
        so they form a readable row (increment x by w + gap each call).
        """
        aspect_ratio = aspect_ratio or "1:1"
        shot_type = shot_type or "medium shot"

        # ── gather style hints from creator profile ───────────────────────────
        style_hints: dict | None = None
        if creator_id:
            style_profile = db.get_style_profile(creator_id)
            if style_profile:
                prof = style_profile.get("profile") or {}
                if isinstance(prof, dict):
                    style_hints = {
                        "lighting": prof.get("lighting") or prof.get("tone") or "",
                        "palette": prof.get("palette") or [],
                        "mood": (style_profile.get("summary") or "")[:120],
                    }

        # ── generate the image ────────────────────────────────────────────────
        with dev_events.track("image", f"storyboard frame ({shot_type})", detail=concept[:80]):
            png_bytes = image_gen.generate_storyboard_frame(
                concept,
                shot_type=shot_type,
                style_hints=style_hints,
                aspect_ratio=aspect_ratio,
            )

        # ── persist to DB ─────────────────────────────────────────────────────
        frame_id = db.save_storyboard_frame(
            project_id=project_id,
            concept=concept,
            shot_type=shot_type,
            aspect_ratio=aspect_ratio,
            image=png_bytes,
            mime_type="image/png",
        )
        image_url = f"/api/storyboard/{frame_id}"

        # ── create canvas artifact ────────────────────────────────────────────
        # Width/height in canvas units: 16:9 panels are wider than square ones.
        w = 520 if aspect_ratio == "16:9" else 360
        h = 300 if aspect_ratio == "16:9" else 360

        artifact = db.create_artifact(
            project_id=project_id,
            type_="frame",
            title=concept[:60] + ("…" if len(concept) > 60 else ""),
            payload={
                "role": "storyboard",
                "storyboard_frame_id": frame_id,
                "elements": [
                    {
                        "id": f"img-{frame_id}",
                        "type": "image",
                        "src": image_url,
                        "x": 0,
                        "y": 0,
                        "w": w,
                        "h": h,
                        "concept": concept,
                        "shot_type": shot_type,
                    }
                ],
            },
            position=position,
        )

        return {
            "storyboard_frame_id": frame_id,
            "image_url": image_url,
            "artifact_id": artifact["artifact_id"],
            "concept": concept,
            "shot_type": shot_type,
        }

    @mcp.tool()
    def list_storyboard_frames(project_id: str) -> list:
        """
        List all storyboard frames generated for a project.

        Returns [{storyboard_frame_id, concept, shot_type, aspect_ratio,
        image_url, created_at}] ordered newest first.

        Use this to review what has already been visualised before adding more
        panels, or to surface existing frames when the user asks to see their
        storyboard.
        """
        return db.list_storyboard_frames(project_id)
